### PR TITLE
Mobile Deployment Using GitHub Pages

### PR DESCRIPTION
**Pull request by Medini-Rajendra**
##In this project, I have 
 - Checked for Linter errors
 - Updated Readme file
 - Checked for errors.

### CODE REVIEW

**Review by vichuge — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

mario_ladders

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your README and PR message are descriptive ✔️

## Aspects to improve ♻️

- [x] It looks like you have some problems with your deployment, I invite you to check desktop and mobile size and find diff issues on your deployment. At the same time, it looks like your deployment doesn't refresh when you apply changes, try to add the deployment on the actual branch you're working on, this will help you to see the newest version on your project.
- image
- image


Cheers and Happy coding!👏👏👏

@victor: I have opened the webpage here and it works correctly. I have sent multiple messages on Slack and email. Please reply back to get further clarity

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Medini-Rajendra** [comment]
@vichuge : I have checked multiple times and I had no problem opening the webpage. I tried to reach you over Slack multiple times but got no response. The deployed webpage works correctly without any problems.

**Comment by Medini-Rajendra** [comment]
I have finished all the modifications requested by the reviewer. All changes were fixed and implemented.

**Review by arslanbisharat — APPROVED** [review]
# Approved 👏 

Hi,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

**Pull request merged**
